version: "3.7"
services:
  
  webapp:
    build:
      context: .
      dockerfile: ./webapp.Dockerfile
    expose:
      - 8501
    ports:
      - 8501:8501

  doku:
    build:
      context: .
      dockerfile: ./doku.Dockerfile
    expose:
      - 5000
    ports:
      - 5000:5000


